version: "3"
services:
  wing:
    image: v2fly/v2fly-core
    container_name: wing_v2ray
    volumes:
      - ./logs:/usr/logs
      - ./acme.sh:/acme.sh
      - v2rayConfigVol:/etc/v2ray
    depends_on:
      - ngi
      - init_wing
    ports:
      - 443:443
    networks:
      - way
  init_wing:
    image: nginx
    command: sh -c 'envsubst < /template/config.json > /etc/v2ray/config.json'
    volumes:
      - v2rayConfigVol:/etc/v2ray
      - ./v2ray/config:/template
    env_file:
      - ./env/wing.env
    #  speed:
    #    image: ilemonrain/html5-speedtest:latest
    #    container_name: wing_speed
    #    networks:
    #      - way
  acme:
    image: neilpang/acme.sh
    command: daemon
    container_name: acme
    volumes:
      - ./acme.sh:/acme.sh
    env_file:
      - ./env/dnsapi.env
      - ./env/wing.env
    networks:
      - way
  ngi:
    build:
      context: ./
      dockerfile: nginx/image/Dockerfile
    container_name: wing_nginx
    volumes:
      - ./nginx/conf.d:/template
      - ./html:/var/www/html
      - ./acme.sh:/acme.sh
    env_file:
      - ./env/wing.env
    networks:
      - way
    ports:
      - 80:80
networks:
  way:
volumes:
  v2rayConfigVol: