version: "3"
services:
  wing:
    image: v2fly/v2fly-core:latest
    container_name: wing-v2ray
    volumes:
      - ./v2ray:/etc/v2ray
      - ./logs:/usr/logs
    networks:
      - way
  acme:
    image: neilpang/acme.sh
    command: daemon
    container_name: acme
    volumes:
      - ./acme.sh:/acme.sh
      - ./cert:/cert
    env_file:
      - ./init/dnsapi.env
    environment:
      - DEPLOY_HAPROXY_PEM_PATH=/cert
      - DEPLOY_HAPROXY_RELOAD=echo done
    networks:
      - way
  init:
    image: haproxy:latest
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
      - ./cert:/etc/cert
      - ./init:/init
      - ./v2ray:/v2ray
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker
      - /usr/bin/com.docker.cli:/bin/com.docker.cli
      - ./nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - ./init/dnsapi.env
    networks:
      - way
    command: /init/init.sh
    depends_on: 
      - acme
  ngi:
    image: nginx:latest
    container_name: wing_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
    networks: 
      - way
    ports: 
      - 80:80
  ha:
    image: haproxy:latest
    container_name: wing_haproxy
    volumes: 
      - ./logs:/usr/logs
      - ./haproxy:/usr/local/etc/haproxy
      - ./cert:/etc/cert
    networks: 
      - way
    ports: 
      - 443:443
    depends_on: 
      - init
networks:
  way:
