version: "3"
services:
  wing:
    image: v2ray/official:latest
    volumes:
      - ./v2ray:/etc/v2ray
      - ./logs:/usr/logs
    networks:
      - way
  ngi:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
    networks: 
      - way
    ports: 
      - 80:80
  ha:
    image: haproxy:latest
    volumes: 
      - ./logs:/usr/logs
      - ./haproxy:/usr/local/etc/haproxy
      - ./cert:/etc/cert
    networks: 
      - way
    ports: 
      - 443:443
networks:
  way:
